Editor_Path = "c:\\Unreal\\UE_5.5\\Engine\\Binaries\\Win64\\UnrealEditor.exe"
Project_Path = "f:\\Work\\Unreal_Engine\\Unreal_Projects\\Automation\\Automation.uproject"
Tests_Log_Path = "f:\\Work\\Unreal_Engine\\Unreal_Projects\\Automation\\Build\\Tests\\Tests.log"
UE_Automation_Content_Path = "c:\\Unreal\\UE_5.5\\Engine\\Content\\Automation\\"
Report_Output_Path = "f:\\Work\\Unreal_Engine\\Unreal_Projects\\Automation\\Build\\Tests"
Tests_Data_Path = "f:\\Work\\Unreal_Engine\\Unreal_Projects\\Automation\\devops\\data"
Source_Path = "f:\\Work\\Unreal_Engine\\Unreal_Projects\\Automation\\Source"
Open_CPP_Coverage_Path = '"C:\\Program Files\\OpenCppCoverage\\OpenCppCoverage.exe"'
Project_Root_Path = "f:\\Work\\Unreal_Engine\\Unreal_Projects\\Automation"
Coverage_Output_Path = "f:\\Work\\Unreal_Engine\\Unreal_Projects\\Automation\\Build\\Tests\\Coverage\\Code_Coverage"
Coverage_Export_Type = "html"
Server_Port = 8081
